### ISSUE TITLE
[Request] Netherite extras' nuggets and create deco nuggets

### ISSUE THREAD

**Issue by Plasman888** [MrRedstoneToGo/CreateDecoAdditions#2]
Pls add compatibility between the netherite nuggets from create deco and the netherite nuggets from netherite extras

**Comment by BugInYourCode01** [comment]
Should now be fixed now on Netherite Extras' side.

**Comment by BugInYourCode01** [comment]
As with the zinc plates, one of the Netherite nuggets is unobtainable, but both can be used in any recipe now.

**Comment by SLH335** [comment]
Hi, I'm the creator of Netherite Extras. Thank you for reporting this issue and thanks to MrRedstoneToGo for submitting the fix. I've merged the changes and they will be included in the next release of Netherite Extras. That means that the two Netherite Nuggets will be compatible once Create and Create Deco have updated to 1.21.1. I typically don't backport new features to older versions of Minecraft, since that would be quite a lot of additional work.

**Comment by Plasman888** [comment]
Oh so it wont be done for 1.20.1?

**Comment by SLH335** [comment]
I can publish a new minor release for 1.20.1 including the fix if you want me to, that's not a problem. I mainly mean, that I don't plan to backport new features of the mod to older Minecraft versions, at least not currently.

**Comment by Plasman888** [comment]
ahh thats fine

**Comment by Plasman888** [comment]
though the nugget config would be useful

**Comment by BugInYourCode01** [comment]
> Hi, I'm the creator of Netherite Extras. Thank you for reporting this issue and thanks to MrRedstoneToGo for submitting the fix. I've merged the changes and they will be included in the next release of Netherite Extras. That means that the two Netherite Nuggets will be compatible once Create and Create Deco have updated to 1.21.1. I typically don't backport new features to older versions of Minecraft, since that would be quite a lot of additional work.

The tags do not add compatibility to the "vanilla" Create Deco mod, because Create Deco uses weird tags ("createdeco:internal/nuggets/netherite") just so the devs don't have to change them with the different mod loaders. If you want, I can tell you how to add Create Deco's weird tag, it's just a matter of copy-pasting ;-)
However, when I have enough time and desire to learn modding - I already know Java - and especially data generation (that's why my pull request didn't get merged into their code), I'll start another pull request on their GitHub page, so the effort isn't really needed; just use this datapack.

**Comment by Plasman888** [comment]
Which datapack?

**Comment by MrRedstoneToGo** [comment]
Create Deco Additions, the project to which the issue you're looking at belongs, is a datapack I created to change the tags from Create Deco to those used by the Forge or Fabric ecosystems. It is also available on modrinth [here] (https://modrinth.com/datapack/create-deco-additions).

**Comment by BugInYourCode01** [comment]
The project to which the issue you are currently viewing belongs. You can also find it on modrinth [here](https://modrinth.com/datapack/create-deco-additions).
